# site settings
locale                   : "en-US"
title                    : "Chloe Rickards"
title_separator          : "-"
name                     : &name "Chloe Rickards"
description              : &description "I am a data scientist and an artist and this is my portfolio. Thanks for visiting!"
url                      : https://chloerickards.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
subtitle: DATA & ART
email: rickards.chloe@gmail.com
author:
country: United States of America

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 2

tiles:
  - title: Data
    image: assets/images/leftbrain.jpg
    url: /data/  # This MUST match the permalink in your data.md file
    description: "Interactive R Shiny apps and data visualization projects."

  - title: Art
    image: assets/images/rightbrain.jpg
    url: /art/  # This MUST match the permalink in your art.md file
    description: "A selection of my paintings and digital creations."

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/chloerickards
  GitLab:
  Google-Plus: 
  Instagram: https://www.instagram.com/clo.makes.art/?hl=en
  LinkedIn: https://www.linkedin.com/in/chloegr
  Twitter: 
  Facebook:
  Slack:
  Envelope: mailto:{{rickards.chloe@gmail.com}}

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
